import fs from "node:fs/promises";
import path from "node:path";
import { decryptSecret } from "./crypto.mjs";

function radiusQuote(value) {
  return String(value ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/[\r\n]/g, " ");
}

export function normalizeMac(value) {
  const raw = String(value || "").toLowerCase().replace(/[^0-9a-f]/g, "");
  if (!/^[0-9a-f]{12}$/.test(raw)) return "";
  return raw;
}

export function macVariants(value) {
  const raw = normalizeMac(value);
  if (!raw) return [];
  const pairs = raw.match(/../g);
  return [...new Set([
    raw,
    raw.toUpperCase(),
    pairs.join(":"),
    pairs.join(":").toUpperCase(),
    pairs.join("-"),
    pairs.join("-").toUpperCase(),
    `${raw.slice(0,4)}.${raw.slice(4,8)}.${raw.slice(8)}`,
    `${raw.slice(0,4)}.${raw.slice(4,8)}.${raw.slice(8)}`.toUpperCase(),
  ])];
}

function vlanReply(vlan) {
  if (!vlan) return [];
  return [
    "    Tunnel-Type := VLAN,",
    "    Tunnel-Medium-Type := IEEE-802,",
    `    Tunnel-Private-Group-Id := "${Number(vlan)}"`,
  ];
}

export function buildClientsConfig(networks) {
  const lines = ["# Generated by EMS IPAM. Do not edit manually."];
  for (const item of networks.filter((row) => row.enabled)) {
    let secret = "";
    try { secret = decryptSecret(item.secret_ciphertext ?? item.secretCiphertext); } catch { continue; }
    lines.push("", `client ems_${String(item.id).replace(/[^A-Za-z0-9_]/g, "_")} {`, `    ipaddr = ${item.cidr}`, `    secret = "${radiusQuote(secret)}"`, "    require_message_authenticator = auto", "}");
  }
  return `${lines.join("\n")}\n`;
}

export function buildAuthorizeConfig({ users, macs, settings }) {
  const lines = ["# Generated by EMS IPAM. Do not edit manually."];
  for (const user of users.filter((row) => row.enabled)) {
    let password = "";
    try { password = decryptSecret(user.password_ciphertext ?? user.passwordCiphertext); } catch { continue; }
    const checks = [`${user.username} Cleartext-Password := "${radiusQuote(password)}"`];
    const replies = [];
    if (user.mikrotik_access && user.mikrotik_access !== "none") replies.push(`    Mikrotik-Group := "${radiusQuote(user.mikrotik_access)}"`);
    if (Number(user.cisco_privilege || 0) > 0) replies.push(`    Cisco-AVPair += "shell:priv-lvl=${Number(user.cisco_privilege)}"`);
    if (user.nexus_role && user.nexus_role !== "none") replies.push(`    Cisco-AVPair += "shell:roles=\\\"${radiusQuote(user.nexus_role)}\\\""`);
    lines.push("", checks[0]);
    if (replies.length) lines.push(replies.join(",\n"));
  }
  // Explicitly disabled/blocked records must win over the global unknown-MAC policy.
  for (const mac of macs.filter((row) => !row.enabled || row.access_mode === "block")) {
    for (const variant of macVariants(mac.mac)) lines.push("", `${variant} Auth-Type := Reject`);
  }
  for (const mac of macs.filter((row) => row.enabled && row.access_mode !== "block")) {
    const replies = mac.access_mode === "allow_vlan" ? vlanReply(mac.vlan) : [];
    for (const variant of macVariants(mac.mac)) {
      lines.push("", `${variant} Auth-Type := Accept`);
      if (replies.length) lines.push(replies.join("\n"));
    }
  }
  const policy = settings?.unknown_mac_policy || "reject";
  if (policy === "allow" || policy === "quarantine") {
    lines.push("", "DEFAULT User-Name =~ /^[0-9A-Fa-f:.\\-]{12,17}$/, Auth-Type := Accept");
    if (policy === "quarantine") lines.push(...vlanReply(settings?.quarantine_vlan));
  }
  return `${lines.join("\n")}\n`;
}

export async function renderRadiusFiles(pool, options = {}) {
  const [networks, users, macs, settings] = await Promise.all([
    pool.query("SELECT id,name,cidr,vendor,secret_ciphertext,enabled FROM radius_networks ORDER BY cidr"),
    pool.query("SELECT id,username,password_ciphertext,account_type,mikrotik_access,cisco_privilege,nexus_role,enabled FROM radius_users ORDER BY username"),
    pool.query("SELECT id,mac,access_mode,vlan,enabled FROM radius_mac_clients ORDER BY mac"),
    pool.query("SELECT unknown_mac_policy,quarantine_vlan,radius_server_ip,keep_mac_history FROM radius_settings WHERE singleton=true"),
  ]);
  const clients = buildClientsConfig(networks.rows);
  const authorize = buildAuthorizeConfig({ users: users.rows, macs: macs.rows, settings: settings.rows[0] || {} });
  const clientsPath = options.clientsPath || process.env.RADIUS_CLIENTS_FILE || "/etc/freeradius/3.0/clients.d/ems-clients.conf";
  const authorizePath = options.authorizePath || process.env.RADIUS_AUTHORIZE_FILE || "/etc/freeradius/3.0/mods-config/files/authorize";
  await fs.mkdir(path.dirname(clientsPath), { recursive: true });
  await fs.mkdir(path.dirname(authorizePath), { recursive: true });
  await fs.writeFile(clientsPath, clients, { mode: 0o600 });
  await fs.writeFile(authorizePath, authorize, { mode: 0o600 });
  return { clientsPath, authorizePath, networks: networks.rowCount, users: users.rowCount, macs: macs.rowCount };
}
